"""empty message

Revision ID: ba28e88b69d9
Revises: df289a2dd953
Create Date: 2024-07-13 19:10:35.806747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba28e88b69d9'
down_revision: Union[str, None] = 'df289a2dd953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('gender', sa.String(), nullable=True))
    op.create_index(op.f('ix_todos_gender'), 'todos', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_gender'), table_name='todos')
    op.drop_column('todos', 'gender')
    # ### end Alembic commands ###
