"""empty message

Revision ID: f15ec71247b4
Revises: ba28e88b69d9
Create Date: 2024-07-13 19:12:49.802746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15ec71247b4'
down_revision: Union[str, None] = 'ba28e88b69d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_todos_age'), 'todos', ['age'], unique=False)
    op.create_index(op.f('ix_todos_gender'), 'todos', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_gender'), table_name='todos')
    op.drop_index(op.f('ix_todos_age'), table_name='todos')
    op.drop_column('todos', 'age')
    op.drop_column('todos', 'gender')
    # ### end Alembic commands ###
